public class Planet {

    private static final int HEIGHT = 21;
    private static final int WIDTH = 21;

    Cell[][] cells;

    public Planet() {
        System.out.println("Instanciation de la planète.");
        this.cells = new Cell[HEIGHT][WIDTH];
        int x,y;

        for(y=0;y<HEIGHT;y++){
            for(x=0;x<WIDTH;x++){
                cells[y][x] = new Cell(new Coord(y,x),State.MINERAI);
            }
        }

        State[][] states = {
                {State.LAC,State.LAC,State.LAC,State.LAC,State.PRAIRIE_SECHE,State.PRAIRIE_GRASSE,State.DESERT,State.DESERT,State.DESERT,State.DESERT,State.DESERT,State.DESERT,State.PRAIRIE_GRASSE,State.PRAIRIE_SECHE,State.PRAIRIE_SECHE,State.PRAIRIE_SECHE,State.PRAIRIE_GRASSE,State.PRAIRIE_SECHE,State.PRAIRIE_SECHE,State.MINERAI,State.PIERRAILLE},
                {State.LAC,State.LAC,State.PRAIRIE_SECHE,State.PRAIRIE_SECHE,State.PRAIRIE_SECHE,State.PRAIRIE_GRASSE,State.DESERT,State.DESERT,State.DESERT,State.DESERT,State.PRAIRIE_SECHE,State.PRAIRIE_GRASSE,State.PRAIRIE_GRASSE,State.PRAIRIE_GRASSE,State.PRAIRIE_SECHE,State.PRAIRIE_GRASSE,State.PRAIRIE_SECHE,State.PRAIRIE_SECHE,State.NOURRITURE,State.PIERRAILLE,State.PIERRAILLE},
                {State.LAC,State.PRAIRIE_SECHE,State.PRAIRIE_GRASSE,State.PRAIRIE_GRASSE,State.PRAIRIE_GRASSE,State.PRAIRIE_SECHE,State.DESERT,State.DESERT,State.DESERT,State.PRAIRIE_SECHE,State.PRAIRIE_GRASSE,State.PRAIRIE_GRASSE,State.PRAIRIE_GRASSE,State.PRAIRIE_GRASSE,State.PRAIRIE_GRASSE,State.PRAIRIE_GRASSE,State.PRAIRIE_GRASSE,State.PRAIRIE_NORMALE,State.PIERRAILLE,State.LAC,State.PIERRAILLE},
                {State.LAC,State.PIERRAILLE,State.PRAIRIE_GRASSE,State.PRAIRIE_GRASSE,State.PRAIRIE_SECHE,State.PRAIRIE_SECHE,State.DESERT,State.DESERT,State.ZONE_INFRANCHISSABLE,State.PRAIRIE_SECHE,State.PRAIRIE_GRASSE,State.LAC,State.PRAIRIE_GRASSE,State.PRAIRIE_GRASSE,State.PRAIRIE_GRASSE,State.PRAIRIE_GRASSE,State.PRAIRIE_GRASSE,State.PRAIRIE_NORMALE,State.PIERRAILLE,State.PIERRAILLE,State.NOURRITURE},
                {State.PRAIRIE_SECHE,State.PIERRAILLE,State.PIERRAILLE,State.PIERRAILLE,State.PRAIRIE_SECHE,State.PRAIRIE_SECHE,State.PRAIRIE_SECHE,State.DESERT,State.PRAIRIE_SECHE,State.PRAIRIE_SECHE,State.PRAIRIE_GRASSE,State.LAC,State.LAC,State.PRAIRIE_GRASSE,State.NOURRITURE,State.PRAIRIE_NORMALE,State.PRAIRIE_NORMALE,State.PRAIRIE_NORMALE,State.LAC,State.LAC,State.LAC},
                {State.PRAIRIE_SECHE,State.PRAIRIE_SECHE,State.PRAIRIE_GRASSE,State.PIERRAILLE,State.PIERRAILLE,State.PIERRAILLE,State.PRAIRIE_GRASSE,State.PRAIRIE_SECHE,State.PRAIRIE_SECHE,State.PRAIRIE_SECHE,State.PRAIRIE_GRASSE,State.PRAIRIE_GRASSE,State.PRAIRIE_GRASSE,State.NOURRITURE,State.PRAIRIE_GRASSE,State.PRAIRIE_NORMALE,State.ZONE_INFRANCHISSABLE,State.LAC,State.LAC,State.LAC,State.PRAIRIE_NORMALE},
                {State.PRAIRIE_GRASSE,State.PRAIRIE_SECHE,State.PIERRAILLE,State.PIERRAILLE,State.PIERRAILLE,State.MINERAI,State.PRAIRIE_GRASSE,State.PRAIRIE_NORMALE,State.PRAIRIE_NORMALE,State.PRAIRIE_NORMALE,State.PRAIRIE_GRASSE,State.PRAIRIE_GRASSE,State.PRAIRIE_GRASSE,State.PRAIRIE_GRASSE,State.PRAIRIE_GRASSE,State.PRAIRIE_GRASSE,State.LAC,State.LAC,State.LAC,State.PRAIRIE_NORMALE,State.PRAIRIE_GRASSE},
                {State.PRAIRIE_SECHE,State.PRAIRIE_SECHE,State.PIERRAILLE,State.MINERAI,State.PIERRAILLE,State.PIERRAILLE,State.PIERRAILLE,State.PIERRAILLE,State.PRAIRIE_NORMALE,State.PRAIRIE_GRASSE,State.PRAIRIE_GRASSE,State.PRAIRIE_GRASSE,State.PRAIRIE_GRASSE,State.PRAIRIE_GRASSE,State.PRAIRIE_GRASSE,State.PRAIRIE_GRASSE,State.PIERRAILLE,State.LAC,State.PRAIRIE_NORMALE,State.PRAIRIE_GRASSE,State.PRAIRIE_GRASSE},
                {State.PRAIRIE_GRASSE,State.PRAIRIE_SECHE,State.PRAIRIE_SECHE,State.PRAIRIE_SECHE,State.PRAIRIE_SECHE,State.PIERRAILLE,State.PIERRAILLE,State.PIERRAILLE,State.PRAIRIE_GRASSE,State.PRAIRIE_SECHE,State.PRAIRIE_NORMALE,State.PRAIRIE_SECHE,State.PRAIRIE_NORMALE,State.PRAIRIE_NORMALE,State.PIERRAILLE,State.PIERRAILLE,State.PRAIRIE_GRASSE,State.NOURRITURE,State.PRAIRIE_GRASSE,State.PRAIRIE_NORMALE,State.PRAIRIE_NORMALE},
                {State.PRAIRIE_SECHE,State.PRAIRIE_GRASSE,State.PRAIRIE_SECHE,State.PRAIRIE_SECHE,State.PRAIRIE_SECHE,State.PRAIRIE_SECHE,State.PRAIRIE_SECHE,State.PIERRAILLE,State.PRAIRIE_GRASSE,State.PRAIRIE_GRASSE,State.PIERRAILLE,State.PRAIRIE_GRASSE,State.PRAIRIE_GRASSE,State.PIERRAILLE,State.PIERRAILLE,State.PRAIRIE_GRASSE,State.PRAIRIE_GRASSE,State.PRAIRIE_GRASSE,State.PRAIRIE_GRASSE,State.PRAIRIE_NORMALE,State.PRAIRIE_NORMALE},
                {State.FORET,State.PRAIRIE_SECHE,State.PRAIRIE_GRASSE,State.PRAIRIE_SECHE,State.PRAIRIE_SECHE,State.PRAIRIE_SECHE,State.ZONE_INFRANCHISSABLE,State.PIERRAILLE,State.PIERRAILLE,State.PRAIRIE_GRASSE,State.BASE,State.PIERRAILLE,State.PIERRAILLE,State.PRAIRIE_GRASSE,State.PRAIRIE_GRASSE,State.PRAIRIE_SECHE,State.PRAIRIE_SECHE,State.PRAIRIE_GRASSE,State.PRAIRIE_NORMALE,State.LAC,State.LAC},
                {State.FORET,State.PRAIRIE_GRASSE,State.PRAIRIE_GRASSE,State.PRAIRIE_SECHE,State.PRAIRIE_GRASSE,State.PRAIRIE_GRASSE,State.PRAIRIE_SECHE,State.PRAIRIE_SECHE,State.PIERRAILLE,State.LAC,State.PIERRAILLE,State.PIERRAILLE,State.PRAIRIE_NORMALE,State.PRAIRIE_GRASSE,State.PRAIRIE_GRASSE,State.PRAIRIE_NORMALE,State.LAC,State.PRAIRIE_NORMALE,State.LAC,State.LAC,State.PRAIRIE_NORMALE},
                {State.FORET,State.PRAIRIE_GRASSE,State.PRAIRIE_SECHE,State.LAC,State.PRAIRIE_SECHE,State.PRAIRIE_SECHE,State.PRAIRIE_GRASSE,State.PRAIRIE_SECHE,State.PRAIRIE_GRASSE,State.PRAIRIE_GRASSE,State.PIERRAILLE,State.PIERRAILLE,State.PRAIRIE_NORMALE,State.PRAIRIE_NORMALE,State.NOURRITURE,State.LAC,State.PRAIRIE_NORMALE,State.PRAIRIE_NORMALE,State.LAC,State.FORET,State.FORET},
                {State.FORET,State.PRAIRIE_GRASSE,State.PRAIRIE_GRASSE,State.PRAIRIE_NORMALE,State.NOURRITURE,State.LAC,State.PRAIRIE_GRASSE,State.PRAIRIE_GRASSE,State.PRAIRIE_GRASSE,State.NOURRITURE,State.PIERRAILLE,State.PRAIRIE_GRASSE,State.PIERRAILLE,State.PRAIRIE_NORMALE,State.PRAIRIE_NORMALE,State.NOURRITURE,State.FORET,State.FORET,State.FORET,State.FORET,State.FORET},
                {State.PRAIRIE_GRASSE,State.PRAIRIE_GRASSE,State.PRAIRIE_GRASSE,State.NOURRITURE,State.NOURRITURE,State.LAC,State.PRAIRIE_GRASSE,State.PRAIRIE_GRASSE,State.PRAIRIE_GRASSE,State.PRAIRIE_GRASSE,State.PRAIRIE_GRASSE,State.MINERAI,State.PIERRAILLE,State.PRAIRIE_NORMALE,State.PRAIRIE_SECHE,State.FORET,State.FORET,State.FORET,State.FORET,State.FORET,State.PRAIRIE_GRASSE},
                {State.PRAIRIE_GRASSE,State.NOURRITURE,State.NOURRITURE,State.PRAIRIE_GRASSE,State.LAC,State.LAC,State.PRAIRIE_GRASSE,State.ZONE_INFRANCHISSABLE,State.PRAIRIE_GRASSE,State.PRAIRIE_GRASSE,State.PRAIRIE_GRASSE,State.PIERRAILLE,State.PIERRAILLE,State.PRAIRIE_SECHE,State.PRAIRIE_NORMALE,State.FORET,State.FORET,State.PRAIRIE_GRASSE,State.FORET,State.PRAIRIE_GRASSE,State.PRAIRIE_NORMALE},
                {State.LAC,State.LAC,State.PRAIRIE_GRASSE,State.PRAIRIE_GRASSE,State.PRAIRIE_SECHE,State.PRAIRIE_SECHE,State.PRAIRIE_GRASSE,State.PRAIRIE_GRASSE,State.PIERRAILLE,State.PIERRAILLE,State.PIERRAILLE,State.PIERRAILLE,State.PIERRAILLE,State.PIERRAILLE,State.PRAIRIE_NORMALE,State.PRAIRIE_GRASSE,State.PRAIRIE_GRASSE,State.PRAIRIE_GRASSE,State.NOURRITURE,State.PRAIRIE_SECHE,State.PRAIRIE_SECHE},
                {State.PRAIRIE_NORMALE,State.PRAIRIE_NORMALE,State.PRAIRIE_NORMALE,State.PRAIRIE_NORMALE,State.PRAIRIE_NORMALE,State.PIERRAILLE,State.PIERRAILLE,State.PIERRAILLE,State.PIERRAILLE,State.PIERRAILLE,State.PRAIRIE_GRASSE,State.PRAIRIE_NORMALE,State.PRAIRIE_NORMALE,State.PIERRAILLE,State.PIERRAILLE,State.PIERRAILLE,State.PRAIRIE_SECHE,State.PRAIRIE_GRASSE,State.PRAIRIE_NORMALE,State.PRAIRIE_NORMALE,State.LAC},
                {State.PRAIRIE_GRASSE,State.PRAIRIE_NORMALE,State.PIERRAILLE,State.PIERRAILLE,State.PIERRAILLE,State.PIERRAILLE,State.PIERRAILLE,State.PRAIRIE_GRASSE,State.PRAIRIE_NORMALE,State.PRAIRIE_GRASSE,State.PRAIRIE_GRASSE,State.PRAIRIE_GRASSE,State.PRAIRIE_GRASSE,State.PRAIRIE_GRASSE,State.PRAIRIE_GRASSE,State.PIERRAILLE,State.PIERRAILLE,State.PIERRAILLE,State.LAC,State.LAC,State.LAC},
                {State.LAC,State.PIERRAILLE,State.PIERRAILLE,State.LAC,State.LAC,State.PRAIRIE_GRASSE,State.PRAIRIE_GRASSE,State.PRAIRIE_GRASSE,State.LAC,State.LAC,State.PRAIRIE_NORMALE,State.PRAIRIE_GRASSE,State.PRAIRIE_GRASSE,State.PRAIRIE_GRASSE,State.PRAIRIE_GRASSE,State.PRAIRIE_GRASSE,State.MINERAI,State.PIERRAILLE,State.PIERRAILLE,State.LAC,State.LAC},
                {State.PIERRAILLE,State.PIERRAILLE,State.LAC,State.PRAIRIE_GRASSE,State.ZONE_INFRANCHISSABLE,State.NOURRITURE,State.PRAIRIE_GRASSE,State.PRAIRIE_NORMALE,State.PRAIRIE_SECHE,State.PRAIRIE_SECHE,State.PRAIRIE_GRASSE,State.PRAIRIE_GRASSE,State.PRAIRIE_GRASSE,State.PRAIRIE_GRASSE,State.PRAIRIE_GRASSE,State.PRAIRIE_GRASSE,State.PRAIRIE_SECHE,State.LAC,State.LAC,State.LAC,State.LAC}
        };


        for(y=0;y<HEIGHT;y++){
            for(x=0;x<WIDTH;x++){
                cells[y][x].setState(states[y][x]);
            }
        }
    }

    public void metamorphose(int transformation_percentage){
        int x,y,rand;

        for(y=0;y<HEIGHT;y++){
            for(x=0;x<WIDTH;x++){
                rand = (int)(Math.random() * 101);
                System.out.println(rand);
                if(rand < transformation_percentage){
                    cells[y][x].setState(pick_state(cells[y][x].getState()));
                }
            }
        }
    }

    public State pick_state(State s) {
        return State.LAC;
    }
}
